server.port=6060
spring.application.name=toista
spring.datasource.url=jdbc:postgresql://localhost:5432/arnet_prod
spring.datasource.username=postgres
spring.datasource.password=332000
spring.datasource.initialization-mode=always
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
security.jwt.enabled=true
